apiVersion: v1
kind: ConfigMap
metadata:
  name: example-reloadable-configmap
  namespace: default
data:
  example.application.properties: |-
    reloadable.property=Hello, I'm loaded by Spring Kubernetes, you can reload me!
