apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-test-app
  labels:
    app: configmap-test-app
spec:
  replicas: 1
  template:
    metadata:
      name: configmap-test-app
      labels:
        app: configmap-test-app
    spec:
      containers:
        - name: configmap-test-app
          image: smart-ticketing/configmap
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: spring-cloud-cubernetes-profile
      restartPolicy: Always
  selector:
    matchLabels:
      app: configmap-test-app
