apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-test-app
  labels:
    app: configmap-test-app
spec:
  replicas: 1
  template:
    metadata:
      name: configmap-test-app
      labels:
        app: configmap-test-app
    spec:
      containers:
        - name: configmap-test-app
          image: smart-ticketing/configmap
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: sercrets-profile
          volumeMounts:
            - mountPath: /secrets-volume
              name: secrets-volume
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: secrets-volume
          secret:
            secretName: example-secret
  selector:
    matchLabels:
      app: configmap-test-app
